; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

# Velocidade do Monitor Serial para corresponder a Serial.begin()
monitor_speed = 115200

upload_speed = 921600

; build_unflags = -O1 -O2 -O3 -Og -O -Ofast -Os
build_flags = 
    -Ofast                      ; Otimiza velocidade
    -Wl,--gc-sections        ; Linker: Remove ("Garbage Collect") funções e dados não utilizados
    -ffunction-sections      ; Compilador: Coloca cada função em sua própria seção
    -fdata-sections          ; Compilador: Coloca cada variável em sua própria seção
    -fno-exceptions          ; Desabilita o suporte a exceções do C++, economiza muito espaço
    -fno-rtti                ; Desabilita informações de tipo em tempo de execução (RTTI) do C++
    -I include               ; Adiciona seu diretório 'include' ao path
    -I lib                   ; Adiciona seu diretório 'lib' ao path
    -D ARDUINO_EIGEN_USE_STL

# Dependências de bibliotecas a serem baixadas pelo PlatformIO
lib_deps = 
    adafruit/Adafruit BMP280 Library
    ESP32Servo
    LowPowerLab/SPIFlash
    ArduinoEigen
# Modo do Library Dependency Finder (LDF)
lib_ldf_mode = chain