; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc1-n16r8]
platform = espressif32
board = esp32-s3-devkitc1-n16r8
framework = arduino
board_build.partitions = partitions_16MB_littlefs.csv
board_upload.flash_size = 16MB
board_build.f_flash = 80000000L  ; 80MHz
board_build.flash_mode = qio     ; Quad I/O

monitor_speed = 115200
# With CDC_ON_BOOT=0, Serial uses UART0 via the CH340 "UART" port on the DevKit.
# Use the UART port for Serial Monitor.
# The native USB port is still used for Upload.
monitor_rts = 0
monitor_dtr = 0

upload_speed = 921600

; build_unflags = -O1 -O2 -O3 -Og -O -Ofast -Os
build_flags = 
    -Ofast                   ; Otimiza velocidade
    -Wl,--gc-sections        ; Linker: Remove ("Garbage Collect") funções e dados não utilizados
    -ffunction-sections      ; Compilador: Coloca cada função em sua própria seção
    -fdata-sections          ; Compilador: Coloca cada variável em sua própria seção
    -fno-exceptions          ; Desabilita o suporte a exceções do C++, economiza muito espaço
    -I include               ; Adiciona seu diretório 'include' ao path
    -I lib                   ; Adiciona seu diretório 'lib' ao path
    -D ARDUINO_USB_CDC_ON_BOOT=0 ; 0=UART Serial (CH340 port) | 1=USB-CDC (causes hardware ROM resets)
    -D ARDUINO_USB_MODE=1          ; 1=Hardware CDC/JTAG
    -D ARDUINO_SERIAL_CDC_TX_BUFFER_SIZE=2048 
    -D ARDUINO_SERIAL_CDC_RX_BUFFER_SIZE=512  
    -D ARDUINO_EIGEN_USE_STL
    -D CONFIG_RTC_CLK_SRC_INT_RC=1   ; Ensures GPIO 1/2 aren't stolen by 32k XTAL

# Dependências de bibliotecas a serem baixadas pelo PlatformIO
lib_deps = 
    FS
    LittleFS
    SD_MMC
    adafruit/Adafruit BMP280 Library
    SPIMemory
    ArduinoEigen
    madhephaestus/ESP32Servo

# Modo do Library Dependency Finder (LDF)
lib_ldf_mode = chain